name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name: Build with Maven (compile + test)
      run: |
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        sleep 3
        ./mvnw --batch-mode --update-snapshots verify

    - name: Verify formatting
      run: ./mvnw fmt:check

    - name: Run Checkstyle
      run: ./mvnw checkstyle:check
