# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Install Xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name: Build with Maven
      run: ./mvnw --batch-mode --update-snapshots verify

    - name: Verify formatting
      run: ./mvnw fmt:check

    - name: Run Checkstyle
      run: ./mvnw checkstyle:check

    - name: Run tests
      run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./mvnw test